/* ============================================================
   Euskaltxo — Contenido del curso de euskera (ES → EU)
   Cada unidad tiene palabras {eu, es} y frases {eu, es}.
   Los ejercicios se generan automáticamente a partir de aquí.
   ============================================================ */

const COURSE = [
  {
    id: "saludos",
    title: "Saludos",
    subtitle: "Kaixo! Primeras palabras",
    icon: "👋",
    color: "#58cc02",
    words: [
      { eu: "kaixo", es: "hola" },
      { eu: "agur", es: "adiós" },
      { eu: "bai", es: "sí" },
      { eu: "ez", es: "no" },
      { eu: "eskerrik asko", es: "gracias" },
      { eu: "mesedez", es: "por favor" },
      { eu: "egun on", es: "buenos días" },
      { eu: "arratsalde on", es: "buenas tardes" },
      { eu: "gabon", es: "buenas noches" },
      { eu: "barkatu", es: "perdón" },
    ],
    phrases: [
      { eu: "Kaixo eta ongi etorri", es: "Hola y bienvenido" },
      { eu: "Egun on eta eskerrik asko", es: "Buenos días y gracias" },
      { eu: "Barkatu mesedez", es: "Perdón por favor" },
      { eu: "Agur eta gabon", es: "Adiós y buenas noches" },
    ],
  },
  {
    id: "personas",
    title: "Personas",
    subtitle: "Preséntate en euskera",
    icon: "🙋",
    color: "#1cb0f6",
    words: [
      { eu: "ni", es: "yo" },
      { eu: "zu", es: "tú" },
      { eu: "bera", es: "él" , alt: ["ella"] },
      { eu: "gu", es: "nosotros" },
      { eu: "izena", es: "nombre" },
      { eu: "ondo", es: "bien" },
      { eu: "gaizki", es: "mal" },
      { eu: "laguna", es: "amigo" },
      { eu: "neska", es: "chica" },
      { eu: "mutila", es: "chico" },
    ],
    phrases: [
      { eu: "Ni Ane naiz", es: "Yo soy Ane" },
      { eu: "Zer moduz zaude", es: "Qué tal estás" },
      { eu: "Oso ondo nago", es: "Estoy muy bien" },
      { eu: "Nire izena Jon da", es: "Mi nombre es Jon" },
      { eu: "Zu nire laguna zara", es: "Tú eres mi amigo" },
    ],
  },
  {
    id: "numeros",
    title: "Números",
    subtitle: "Del bat al hamar",
    icon: "🔢",
    color: "#ff9600",
    words: [
      { eu: "bat", es: "uno" },
      { eu: "bi", es: "dos" },
      { eu: "hiru", es: "tres" },
      { eu: "lau", es: "cuatro" },
      { eu: "bost", es: "cinco" },
      { eu: "sei", es: "seis" },
      { eu: "zazpi", es: "siete" },
      { eu: "zortzi", es: "ocho" },
      { eu: "bederatzi", es: "nueve" },
      { eu: "hamar", es: "diez" },
    ],
    phrases: [
      { eu: "Bat bi hiru lau", es: "Uno dos tres cuatro" },
      { eu: "Hiru sagar ditut", es: "Tengo tres manzanas" },
      { eu: "Bost eta bost hamar dira", es: "Cinco y cinco son diez" },
      { eu: "Bi katu ikusten ditut", es: "Veo dos gatos" },
    ],
  },
  {
    id: "colores",
    title: "Colores",
    subtitle: "El mundo en colores",
    icon: "🎨",
    color: "#ce82ff",
    words: [
      { eu: "gorria", es: "rojo" },
      { eu: "urdina", es: "azul" },
      { eu: "berdea", es: "verde" },
      { eu: "horia", es: "amarillo" },
      { eu: "beltza", es: "negro" },
      { eu: "zuria", es: "blanco" },
      { eu: "laranja", es: "naranja" },
      { eu: "morea", es: "morado" },
      { eu: "arrosa", es: "rosa" },
      { eu: "grisa", es: "gris" },
    ],
    phrases: [
      { eu: "Etxea zuria da", es: "La casa es blanca" },
      { eu: "Itsasoa urdina da", es: "El mar es azul" },
      { eu: "Sagarra gorria da", es: "La manzana es roja" },
      { eu: "Katua beltza da", es: "El gato es negro" },
    ],
  },
  {
    id: "familia",
    title: "Familia",
    subtitle: "Ama, aita y compañía",
    icon: "👨‍👩‍👧‍👦",
    color: "#ff4b4b",
    words: [
      { eu: "ama", es: "madre" },
      { eu: "aita", es: "padre" },
      { eu: "semea", es: "hijo" },
      { eu: "alaba", es: "hija" },
      { eu: "amona", es: "abuela" },
      { eu: "aitona", es: "abuelo" },
      { eu: "familia", es: "familia" },
      { eu: "haurra", es: "niño" },
      { eu: "gizona", es: "hombre" },
      { eu: "emakumea", es: "mujer" },
    ],
    phrases: [
      { eu: "Nire ama Miren da", es: "Mi madre es Miren" },
      { eu: "Aitona eta amona etxean daude", es: "El abuelo y la abuela están en casa" },
      { eu: "Nire familia handia da", es: "Mi familia es grande" },
      { eu: "Haurra txikia da", es: "El niño es pequeño" },
    ],
  },
  {
    id: "comida",
    title: "Comida",
    subtitle: "On egin! Buen provecho",
    icon: "🍎",
    color: "#2ec748",
    words: [
      { eu: "ogia", es: "pan" },
      { eu: "ura", es: "agua" },
      { eu: "esnea", es: "leche" },
      { eu: "sagarra", es: "manzana" },
      { eu: "gazta", es: "queso" },
      { eu: "arraina", es: "pescado" },
      { eu: "haragia", es: "carne" },
      { eu: "ardoa", es: "vino" },
      { eu: "kafea", es: "café" },
      { eu: "gosaria", es: "desayuno" },
    ],
    phrases: [
      { eu: "Ogia eta gazta jaten ditut", es: "Como pan y queso" },
      { eu: "Ura edaten dut", es: "Bebo agua" },
      { eu: "Kafea nahi dut mesedez", es: "Quiero café por favor" },
      { eu: "Gosaria oso ona da", es: "El desayuno es muy bueno" },
    ],
  },
  {
    id: "animales",
    title: "Animales",
    subtitle: "Del caserío al monte",
    icon: "🐑",
    color: "#00b8a9",
    words: [
      { eu: "txakurra", es: "perro" },
      { eu: "katua", es: "gato" },
      { eu: "txoria", es: "pájaro" },
      { eu: "zaldia", es: "caballo" },
      { eu: "behia", es: "vaca" },
      { eu: "ardia", es: "oveja" },
      { eu: "hartza", es: "oso" },
      { eu: "otsoa", es: "lobo" },
      { eu: "untxia", es: "conejo" },
      { eu: "sagua", es: "ratón" },
    ],
    phrases: [
      { eu: "Txakurra handia da", es: "El perro es grande" },
      { eu: "Katuak sagua ikusten du", es: "El gato ve al ratón" },
      { eu: "Ardiak mendian daude", es: "Las ovejas están en el monte" },
      { eu: "Txoria ederra da", es: "El pájaro es bonito" },
    ],
  },
  {
    id: "verbos",
    title: "Verbos",
    subtitle: "Acción en euskera",
    icon: "🏃",
    color: "#ff86d0",
    words: [
      { eu: "izan", es: "ser" },
      { eu: "egon", es: "estar" },
      { eu: "joan", es: "ir" },
      { eu: "etorri", es: "venir" },
      { eu: "jan", es: "comer" },
      { eu: "edan", es: "beber" },
      { eu: "hitz egin", es: "hablar" },
      { eu: "ikasi", es: "aprender" },
      { eu: "irakurri", es: "leer" },
      { eu: "idatzi", es: "escribir" },
    ],
    phrases: [
      { eu: "Euskara ikasten dut", es: "Aprendo euskera" },
      { eu: "Liburu bat irakurtzen dut", es: "Leo un libro" },
      { eu: "Etxera joan nahi dut", es: "Quiero ir a casa" },
      { eu: "Euskaraz hitz egiten dugu", es: "Hablamos en euskera" },
    ],
  },
  {
    id: "tiempo",
    title: "Días",
    subtitle: "La semana y el tiempo",
    icon: "📅",
    color: "#8549ba",
    words: [
      { eu: "astelehena", es: "lunes" },
      { eu: "asteartea", es: "martes" },
      { eu: "asteazkena", es: "miércoles" },
      { eu: "osteguna", es: "jueves" },
      { eu: "ostirala", es: "viernes" },
      { eu: "larunbata", es: "sábado" },
      { eu: "igandea", es: "domingo" },
      { eu: "gaur", es: "hoy" },
      { eu: "bihar", es: "mañana" },
      { eu: "atzo", es: "ayer" },
    ],
    phrases: [
      { eu: "Gaur astelehena da", es: "Hoy es lunes" },
      { eu: "Bihar larunbata da", es: "Mañana es sábado" },
      { eu: "Igandean etxean nago", es: "El domingo estoy en casa" },
      { eu: "Atzo ostirala zen", es: "Ayer era viernes" },
    ],
  },
  {
    id: "frases",
    title: "Frases útiles",
    subtitle: "Sobrevive en Euskadi",
    icon: "🗣️",
    color: "#f7c948",
    words: [
      { eu: "non", es: "dónde" },
      { eu: "zenbat", es: "cuánto" },
      { eu: "nor", es: "quién" },
      { eu: "zer", es: "qué" },
      { eu: "etxea", es: "casa" },
      { eu: "kalea", es: "calle" },
      { eu: "herria", es: "pueblo" },
      { eu: "hondartza", es: "playa" },
      { eu: "mendia", es: "monte" },
      { eu: "euria", es: "lluvia" },
    ],
    phrases: [
      { eu: "Non dago komuna", es: "Dónde está el baño" },
      { eu: "Zenbat balio du", es: "Cuánto cuesta" },
      { eu: "Ez dut ulertzen", es: "No entiendo" },
      { eu: "Nongoa zara zu", es: "De dónde eres tú" },
      { eu: "Ni Bilbokoa naiz", es: "Yo soy de Bilbao" },
      { eu: "Maite zaitut", es: "Te quiero" },
    ],
  },
];

// Nº de lecciones por unidad (la última es el repaso/examen de la unidad)
const LESSONS_PER_UNIT = 4;
const EXERCISES_PER_LESSON = 10;
